### ISSUE TITLE
Add source code

### ISSUE THREAD

**Issue by akien-mga** [audiosdev/AudiosPlugin-Godot-iOS-Audio-Plugin#1]
This plugin is documented as under the MIT license, but there's no source code that I can see, only the compiled `.a` library.

**Comment by audiosdev** [comment]
Thanks for your feedback. I have added the source code.

**Comment by audiosdev** [comment]
> This plugin is documented as under the MIT license, but there's no source code that I can see, only the compiled `.a` library.

Thanks for your feedback. I have added the source code.
